server:
  port: 8082
spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: 127.0.0.1 #consul的IP
      port: 8500 #consul启动端口默认8500
      discovery:
        healthCheckPath: /actuator/health  #健康检查路径
        healthCheckInterval: 15s #健康检查频率
        hostname: 127.0.0.1 #注册服务所在IP
        port: ${server.port}  #注册服务所在端口
        service-name: ${spring.application.name} #注册服务名
        register: true #是否启动注册
        register-health-check: true #是否启动健康检查
